/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RunTimeStats.java
 *
 * Created on Mar 6, 2009, 12:48:35 PM
 */

package PET;

/**
 *
 * @author lrochon
 */
public class RunTimeStats extends javax.swing.JPanel {

    /** Creates new form RunTimeStats */
    public RunTimeStats() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RunTimeStatsTP = new javax.swing.JTabbedPane();
        RunTimeStatsSP = new javax.swing.JScrollPane();
        lineWatchView = new PET.LineWatchView();

        setName("Form"); // NOI18N

        RunTimeStatsTP.setName("RunTimeStatsTP"); // NOI18N

        RunTimeStatsSP.setName("RunTimeStatsSP"); // NOI18N

        lineWatchView.setName("lineWatchView"); // NOI18N
        RunTimeStatsSP.setViewportView(lineWatchView);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(PET.PETApp.class).getContext().getResourceMap(RunTimeStats.class);
        RunTimeStatsTP.addTab(resourceMap.getString("RunTimeStatsSP.TabConstraints.tabTitle"), RunTimeStatsSP); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, RunTimeStatsTP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, RunTimeStatsTP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane RunTimeStatsSP;
    private javax.swing.JTabbedPane RunTimeStatsTP;
    private PET.LineWatchView lineWatchView;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lineWatchView
     */
    public PET.LineWatchView getLineWatchView() {
        return lineWatchView;
    }

}
