/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on Mar 30, 2009, 7:57:04 AM
 */
package PET;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.JColorChooser;

/**
 *
 * @author Bhattacharya
 */
public class Settings extends javax.swing.JPanel
{

    private Color codeBGColor, codeFontColor, termBGColor, termFontColor;
    private Color codeRunBGColor, codeRunFontColor, codeLineColor;

    /** Creates new form Settings */
    public Settings()
    {

        initComponents();

        settings_cboxFontSize.removeAllItems();
        settings_fontType.removeAllItems();

        codeBGColor = Color.white;
        codeFontColor = Color.black;

        termBGColor = Color.black;
        termFontColor = Color.green;

        
        for (int i = 8; i <= 28; i++)
        {
            settings_cboxFontSize.addItem(String.format("%d", i));
        }
        


        String[] fontNames = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        for (int i = 0; i < fontNames.length; i++) {
            String name = fontNames[i];
            settings_fontType.addItem(name);
        }

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings_jLabel4 = new javax.swing.JLabel();
        settings_cboxFontSize = new javax.swing.JComboBox();
        settings_jLabel5 = new javax.swing.JLabel();
        settings_fontType = new javax.swing.JComboBox();
        CodeWindowPanel = new javax.swing.JPanel();
        settings_jLabel2 = new javax.swing.JLabel();
        settings_jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCodeBGColor = new javax.swing.JButton();
        ButtonCodeFontColor = new javax.swing.JButton();
        LabelCodeBGColor = new javax.swing.JLabel();
        LabelCodeFontColor = new javax.swing.JLabel();
        settings_jLabel8 = new javax.swing.JLabel();
        settings_jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelCodeRunningFontColor = new javax.swing.JLabel();
        LabelCodeRunningBGColor = new javax.swing.JLabel();
        ButtonCodeRunningFontColor = new javax.swing.JButton();
        ButtonCodeRunningBGColor = new javax.swing.JButton();
        settings_jLabel10 = new javax.swing.JLabel();
        LabelCodeLineColor = new javax.swing.JLabel();
        ButtonCodeLineColor = new javax.swing.JButton();
        TerminalPanel = new javax.swing.JPanel();
        settings_jLabel6 = new javax.swing.JLabel();
        settings_jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelTermBGColor = new javax.swing.JLabel();
        LabelTermFontColor = new javax.swing.JLabel();
        ButtonTermFontColor = new javax.swing.JButton();
        ButtonTermBGColor = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(PET.PETApp.class).getContext().getResourceMap(Settings.class);
        settings_jLabel4.setText(resourceMap.getString("settings_jLabel4.text")); // NOI18N
        settings_jLabel4.setName("settings_jLabel4"); // NOI18N

        settings_cboxFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settings_cboxFontSize.setName("settings_cboxFontSize"); // NOI18N

        settings_jLabel5.setText(resourceMap.getString("settings_jLabel5.text")); // NOI18N
        settings_jLabel5.setName("settings_jLabel5"); // NOI18N

        settings_fontType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        settings_fontType.setName("settings_fontType"); // NOI18N

        CodeWindowPanel.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("CodeWindowPanel.border.lineColor"), 1, true)); // NOI18N
        CodeWindowPanel.setName("CodeWindowPanel"); // NOI18N
        CodeWindowPanel.setPreferredSize(new java.awt.Dimension(250, 100));

        settings_jLabel2.setText(resourceMap.getString("settings_jLabel2.text")); // NOI18N
        settings_jLabel2.setAlignmentY(0.25F);
        settings_jLabel2.setName("settings_jLabel2"); // NOI18N

        settings_jLabel3.setText(resourceMap.getString("settings_jLabel3.text")); // NOI18N
        settings_jLabel3.setAlignmentY(0.25F);
        settings_jLabel3.setName("settings_jLabel3"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        ButtonCodeBGColor.setText(resourceMap.getString("ButtonCodeBGColor.text")); // NOI18N
        ButtonCodeBGColor.setName("ButtonCodeBGColor"); // NOI18N
        ButtonCodeBGColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodeBGColorActionPerformed(evt);
            }
        });

        ButtonCodeFontColor.setText(resourceMap.getString("ButtonCodeFontColor.text")); // NOI18N
        ButtonCodeFontColor.setName("ButtonCodeFontColor"); // NOI18N
        ButtonCodeFontColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodeFontColorActionPerformed(evt);
            }
        });

        LabelCodeBGColor.setBackground(resourceMap.getColor("LabelCodeBGColor.background")); // NOI18N
        LabelCodeBGColor.setText(resourceMap.getString("LabelCodeBGColor.text")); // NOI18N
        LabelCodeBGColor.setName("LabelCodeBGColor"); // NOI18N
        LabelCodeBGColor.setOpaque(true);
        LabelCodeBGColor.setPreferredSize(new java.awt.Dimension(30, 20));

        LabelCodeFontColor.setBackground(resourceMap.getColor("LabelCodeFontColor.background")); // NOI18N
        LabelCodeFontColor.setName("LabelCodeFontColor"); // NOI18N
        LabelCodeFontColor.setOpaque(true);
        LabelCodeFontColor.setPreferredSize(new java.awt.Dimension(30, 20));

        settings_jLabel8.setText(resourceMap.getString("settings_jLabel8.text")); // NOI18N
        settings_jLabel8.setAlignmentY(0.25F);
        settings_jLabel8.setName("settings_jLabel8"); // NOI18N

        settings_jLabel9.setText(resourceMap.getString("settings_jLabel9.text")); // NOI18N
        settings_jLabel9.setAlignmentY(0.25F);
        settings_jLabel9.setName("settings_jLabel9"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        LabelCodeRunningFontColor.setBackground(resourceMap.getColor("LabelCodeRunningFontColor.background")); // NOI18N
        LabelCodeRunningFontColor.setName("LabelCodeRunningFontColor"); // NOI18N
        LabelCodeRunningFontColor.setOpaque(true);
        LabelCodeRunningFontColor.setPreferredSize(new java.awt.Dimension(30, 20));

        LabelCodeRunningBGColor.setBackground(resourceMap.getColor("LabelCodeRunningBGColor.background")); // NOI18N
        LabelCodeRunningBGColor.setName("LabelCodeRunningBGColor"); // NOI18N
        LabelCodeRunningBGColor.setOpaque(true);
        LabelCodeRunningBGColor.setPreferredSize(new java.awt.Dimension(30, 20));

        ButtonCodeRunningFontColor.setText(resourceMap.getString("ButtonCodeRunningFontColor.text")); // NOI18N
        ButtonCodeRunningFontColor.setName("ButtonCodeRunningFontColor"); // NOI18N
        ButtonCodeRunningFontColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodeRunningFontColorActionPerformed(evt);
            }
        });

        ButtonCodeRunningBGColor.setText(resourceMap.getString("ButtonCodeRunningBGColor.text")); // NOI18N
        ButtonCodeRunningBGColor.setName("ButtonCodeRunningBGColor"); // NOI18N
        ButtonCodeRunningBGColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodeRunningBGColorActionPerformed(evt);
            }
        });

        settings_jLabel10.setText(resourceMap.getString("settings_jLabel10.text")); // NOI18N
        settings_jLabel10.setAlignmentY(0.25F);
        settings_jLabel10.setName("settings_jLabel10"); // NOI18N

        LabelCodeLineColor.setBackground(resourceMap.getColor("LabelCodeLineColor.background")); // NOI18N
        LabelCodeLineColor.setName("LabelCodeLineColor"); // NOI18N
        LabelCodeLineColor.setOpaque(true);
        LabelCodeLineColor.setPreferredSize(new java.awt.Dimension(30, 20));

        ButtonCodeLineColor.setText(resourceMap.getString("ButtonCodeLineColor.text")); // NOI18N
        ButtonCodeLineColor.setName("ButtonCodeLineColor"); // NOI18N
        ButtonCodeLineColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCodeLineColorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout CodeWindowPanelLayout = new org.jdesktop.layout.GroupLayout(CodeWindowPanel);
        CodeWindowPanel.setLayout(CodeWindowPanelLayout);
        CodeWindowPanelLayout.setHorizontalGroup(
            CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CodeWindowPanelLayout.createSequentialGroup()
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(CodeWindowPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(CodeWindowPanelLayout.createSequentialGroup()
                                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(CodeWindowPanelLayout.createSequentialGroup()
                                        .add(settings_jLabel2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                                        .add(LabelCodeBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, CodeWindowPanelLayout.createSequentialGroup()
                                        .add(settings_jLabel3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                                        .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(LabelCodeLineColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(LabelCodeFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ButtonCodeLineColor)
                                    .add(ButtonCodeBGColor)
                                    .add(ButtonCodeFontColor)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, CodeWindowPanelLayout.createSequentialGroup()
                                .add(settings_jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                                .add(LabelCodeRunningFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ButtonCodeRunningFontColor))))
                    .add(CodeWindowPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(settings_jLabel10))
                    .add(jLabel3)
                    .add(CodeWindowPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(settings_jLabel9)
                        .add(17, 17, 17)
                        .add(LabelCodeRunningBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ButtonCodeRunningBGColor)))
                .addContainerGap())
        );
        CodeWindowPanelLayout.setVerticalGroup(
            CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CodeWindowPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonCodeBGColor)
                    .add(LabelCodeBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonCodeFontColor)
                    .add(LabelCodeFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelCodeLineColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonCodeLineColor))
                .add(7, 7, 7)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonCodeRunningBGColor)
                    .add(LabelCodeRunningBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CodeWindowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonCodeRunningFontColor)
                    .add(LabelCodeRunningFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        TerminalPanel.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("TerminalPanel.border.lineColor"), 1, true)); // NOI18N
        TerminalPanel.setName("TerminalPanel"); // NOI18N
        TerminalPanel.setPreferredSize(new java.awt.Dimension(250, 100));

        settings_jLabel6.setText(resourceMap.getString("settings_jLabel6.text")); // NOI18N
        settings_jLabel6.setAlignmentY(0.25F);
        settings_jLabel6.setName("settings_jLabel6"); // NOI18N

        settings_jLabel7.setText(resourceMap.getString("settings_jLabel7.text")); // NOI18N
        settings_jLabel7.setAlignmentY(0.25F);
        settings_jLabel7.setName("settings_jLabel7"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        LabelTermBGColor.setBackground(resourceMap.getColor("LabelTermBGColor.background")); // NOI18N
        LabelTermBGColor.setName("LabelTermBGColor"); // NOI18N
        LabelTermBGColor.setOpaque(true);
        LabelTermBGColor.setPreferredSize(new java.awt.Dimension(30, 20));

        LabelTermFontColor.setBackground(resourceMap.getColor("LabelTermFontColor.background")); // NOI18N
        LabelTermFontColor.setName("LabelTermFontColor"); // NOI18N
        LabelTermFontColor.setOpaque(true);
        LabelTermFontColor.setPreferredSize(new java.awt.Dimension(30, 20));

        ButtonTermFontColor.setText(resourceMap.getString("ButtonTermFontColor.text")); // NOI18N
        ButtonTermFontColor.setName("ButtonTermFontColor"); // NOI18N
        ButtonTermFontColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTermFontColorActionPerformed(evt);
            }
        });

        ButtonTermBGColor.setText(resourceMap.getString("ButtonTermBGColor.text")); // NOI18N
        ButtonTermBGColor.setName("ButtonTermBGColor"); // NOI18N
        ButtonTermBGColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTermBGColorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout TerminalPanelLayout = new org.jdesktop.layout.GroupLayout(TerminalPanel);
        TerminalPanel.setLayout(TerminalPanelLayout);
        TerminalPanelLayout.setHorizontalGroup(
            TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TerminalPanelLayout.createSequentialGroup()
                .add(TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(TerminalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(settings_jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(TerminalPanelLayout.createSequentialGroup()
                                .add(LabelTermFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ButtonTermFontColor))
                            .add(TerminalPanelLayout.createSequentialGroup()
                                .add(LabelTermBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ButtonTermBGColor))))
                    .add(TerminalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(settings_jLabel7)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TerminalPanelLayout.setVerticalGroup(
            TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, TerminalPanelLayout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelTermBGColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonTermBGColor))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TerminalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelTermFontColor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ButtonTermFontColor))
                .add(39, 39, 39))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(settings_jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(settings_fontType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(settings_jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(settings_cboxFontSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(CodeWindowPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(TerminalPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(settings_jLabel5)
                    .add(settings_fontType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(settings_jLabel4)
                    .add(settings_cboxFontSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TerminalPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CodeWindowPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCodeBGColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodeBGColorActionPerformed
        this.setCodeBGColor(JColorChooser.showDialog(this, "Choose a color", this.getCodeBGColor()));
        this.LabelCodeBGColor.setBackground(getCodeBGColor());
}//GEN-LAST:event_ButtonCodeBGColorActionPerformed

    private void ButtonCodeFontColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodeFontColorActionPerformed
        this.setCodeFontColor(JColorChooser.showDialog(this, "Choose a color", this.getCodeFontColor()));
        this.LabelCodeFontColor.setBackground(getCodeFontColor());
    }//GEN-LAST:event_ButtonCodeFontColorActionPerformed

    private void ButtonTermFontColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTermFontColorActionPerformed
        this.setTermFontColor(JColorChooser.showDialog(this, "Choose a color", this.getTermFontColor()));
        this.LabelTermFontColor.setBackground(getTermFontColor());
}//GEN-LAST:event_ButtonTermFontColorActionPerformed

    private void ButtonTermBGColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTermBGColorActionPerformed
        this.setTermBGColor(JColorChooser.showDialog(this, "Choose a color", this.getTermBGColor()));
        this.LabelTermBGColor.setBackground(getTermBGColor());
}//GEN-LAST:event_ButtonTermBGColorActionPerformed

    private void ButtonCodeRunningFontColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodeRunningFontColorActionPerformed
        this.setCodeRunFontColor(JColorChooser.showDialog(this, "Choose a color", this.getCodeRunFontColor()));
        this.LabelCodeRunningFontColor.setBackground(getCodeRunFontColor());
}//GEN-LAST:event_ButtonCodeRunningFontColorActionPerformed

    private void ButtonCodeRunningBGColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodeRunningBGColorActionPerformed
        this.setCodeRunBGColor(JColorChooser.showDialog(this, "Choose a color", this.getCodeRunBGColor()));
        this.LabelCodeRunningBGColor.setBackground(getCodeRunBGColor());
}//GEN-LAST:event_ButtonCodeRunningBGColorActionPerformed

    private void ButtonCodeLineColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCodeLineColorActionPerformed
        this.setCodeLineColor(JColorChooser.showDialog(this, "Choose a color", this.getCodeLineColor()));
        this.LabelCodeLineColor.setBackground(getCodeLineColor());
}//GEN-LAST:event_ButtonCodeLineColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCodeBGColor;
    private javax.swing.JButton ButtonCodeFontColor;
    private javax.swing.JButton ButtonCodeLineColor;
    private javax.swing.JButton ButtonCodeRunningBGColor;
    private javax.swing.JButton ButtonCodeRunningFontColor;
    private javax.swing.JButton ButtonTermBGColor;
    private javax.swing.JButton ButtonTermFontColor;
    private javax.swing.JPanel CodeWindowPanel;
    private javax.swing.JLabel LabelCodeBGColor;
    private javax.swing.JLabel LabelCodeFontColor;
    private javax.swing.JLabel LabelCodeLineColor;
    private javax.swing.JLabel LabelCodeRunningBGColor;
    private javax.swing.JLabel LabelCodeRunningFontColor;
    private javax.swing.JLabel LabelTermBGColor;
    private javax.swing.JLabel LabelTermFontColor;
    private javax.swing.JPanel TerminalPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JComboBox settings_cboxFontSize;
    public javax.swing.JComboBox settings_fontType;
    private javax.swing.JLabel settings_jLabel10;
    private javax.swing.JLabel settings_jLabel2;
    private javax.swing.JLabel settings_jLabel3;
    private javax.swing.JLabel settings_jLabel4;
    private javax.swing.JLabel settings_jLabel5;
    private javax.swing.JLabel settings_jLabel6;
    private javax.swing.JLabel settings_jLabel7;
    private javax.swing.JLabel settings_jLabel8;
    private javax.swing.JLabel settings_jLabel9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the codeBGColor
     */
    public Color getCodeBGColor() {
        return codeBGColor;
    }

    /**
     * @param codeBGColor the codeBGColor to set
     */
    public void setCodeBGColor(Color codeBGColor) {
        this.codeBGColor = codeBGColor;
        this.LabelCodeBGColor.setBackground(codeBGColor);
    }

    /**
     * @return the codeFontColor
     */
    public Color getCodeFontColor() {
        return codeFontColor;
    }

    /**
     * @param codeFontColor the codeFontColor to set
     */
    public void setCodeFontColor(Color codeFontColor) {
        this.codeFontColor = codeFontColor;
        this.LabelCodeFontColor.setBackground(codeFontColor);
    }

    /**
     * @return the termBGColor
     */
    public Color getTermBGColor() {
        return termBGColor;
    }

    /**
     * @param termBGColor the termBGColor to set
     */
    public void setTermBGColor(Color termBGColor) {
        this.termBGColor = termBGColor;
        this.LabelTermBGColor.setBackground(termBGColor);
    }

    /**
     * @return the termFontColor
     */
    public Color getTermFontColor() {
        return termFontColor;
    }

    /**
     * @param termFontColor the termFontColor to set
     */
    public void setTermFontColor(Color termFontColor) {
        this.termFontColor = termFontColor;
        this.LabelTermFontColor.setBackground(termFontColor);
    }

    /**
     * @return the codeRunBGColor
     */
    public Color getCodeRunBGColor() {
        return codeRunBGColor;
    }

    /**
     * @param codeRunBGColor the codeRunBGColor to set
     */
    public void setCodeRunBGColor(Color codeRunBGColor) {
        this.codeRunBGColor = codeRunBGColor;
        this.LabelCodeRunningBGColor.setBackground(codeRunBGColor);
    }

    /**
     * @return the codeRunFontColor
     */
    public Color getCodeRunFontColor() {
        return codeRunFontColor;
    }

    /**
     * @param codeRunFontColor the codeRunFontColor to set
     */
    public void setCodeRunFontColor(Color codeRunFontColor) {
        this.codeRunFontColor = codeRunFontColor;
        this.LabelCodeRunningFontColor.setBackground(codeRunFontColor);
    }

    /**
     * @return the codeLineColor
     */
    public Color getCodeLineColor() {
        return codeLineColor;
    }

    /**
     * @param codeLineColor the codeLineColor to set
     */
    public void setCodeLineColor(Color codeLineColor) {
        this.codeLineColor = codeLineColor;
        this.LabelCodeLineColor.setBackground(codeLineColor);
    }

    
}
